spring.application.name=liftlog


spring.datasource.url=jdbc:postgresql://localhost:5432/lift_log
spring.datasource.username=postgres
spring.datasource.password=dhiraj888
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true