/*==============================================================
  DATABASE : LiftLog
  PostgreSQL + Flyway Initial Schema
==============================================================*/

/*==============================================================
  TABLE: users
==============================================================*/

CREATE TABLE users (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    full_name VARCHAR(100) NOT NULL,

    email VARCHAR(255) NOT NULL UNIQUE,

    password_hash VARCHAR(255) NOT NULL,

    gender VARCHAR(20),

    height_cm DECIMAL(5,2),

    date_of_birth DATE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email
ON users(email);


/*==============================================================
  TABLE: muscle_groups
==============================================================*/

CREATE TABLE muscle_groups (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(50) NOT NULL UNIQUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


/*==============================================================
  TABLE: exercises
==============================================================*/

CREATE TABLE exercises (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(150) NOT NULL UNIQUE,

    description TEXT,

    equipment VARCHAR(50),

    difficulty VARCHAR(30),

    primary_muscle_id BIGINT NOT NULL,

    secondary_muscle_id BIGINT,

    video_url VARCHAR(500),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_exercise_primary_muscle
        FOREIGN KEY (primary_muscle_id)
        REFERENCES muscle_groups(id),

    CONSTRAINT fk_exercise_secondary_muscle
        FOREIGN KEY (secondary_muscle_id)
        REFERENCES muscle_groups(id)
);

CREATE INDEX idx_exercise_name
ON exercises(name);

CREATE INDEX idx_exercise_primary_muscle
ON exercises(primary_muscle_id);


/*==============================================================
  TABLE: workout_templates
==============================================================*/

CREATE TABLE workout_templates (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    name VARCHAR(150) NOT NULL,

    notes TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_template_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_template_user
ON workout_templates(user_id);


/*==============================================================
  TABLE: template_exercises
==============================================================*/

CREATE TABLE template_exercises (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    template_id BIGINT NOT NULL,

    exercise_id BIGINT NOT NULL,

    exercise_order INT NOT NULL,

    target_sets INT,

    target_reps VARCHAR(20),

    target_weight DECIMAL(6,2),

    rest_seconds INT,

    CONSTRAINT fk_template_exercise_template
        FOREIGN KEY (template_id)
        REFERENCES workout_templates(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_template_exercise_exercise
        FOREIGN KEY (exercise_id)
        REFERENCES exercises(id),

    CONSTRAINT uk_template_order
        UNIQUE(template_id, exercise_order)
);

CREATE INDEX idx_template_exercise
ON template_exercises(template_id);



/*==============================================================
  TABLE: workout_sessions
==============================================================*/

CREATE TABLE workout_sessions (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    template_id BIGINT,

    started_at TIMESTAMP NOT NULL,

    ended_at TIMESTAMP,

    notes TEXT,

    is_completed BOOLEAN DEFAULT FALSE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_session_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_session_template
        FOREIGN KEY (template_id)
        REFERENCES workout_templates(id)
        ON DELETE SET NULL
);

CREATE INDEX idx_session_user
ON workout_sessions(user_id);

CREATE INDEX idx_session_date
ON workout_sessions(started_at);


/*==============================================================
  TABLE: session_exercises
==============================================================*/

CREATE TABLE session_exercises (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    session_id BIGINT NOT NULL,

    exercise_id BIGINT NOT NULL,

    exercise_order INT NOT NULL,

    notes TEXT,

    CONSTRAINT fk_session_exercise_session
        FOREIGN KEY (session_id)
        REFERENCES workout_sessions(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_session_exercise_exercise
        FOREIGN KEY (exercise_id)
        REFERENCES exercises(id),

    CONSTRAINT uk_session_exercise_order
        UNIQUE(session_id, exercise_order)
);

CREATE INDEX idx_session_exercise
ON session_exercises(session_id);


/*==============================================================
  TABLE: exercise_sets
==============================================================*/

CREATE TABLE exercise_sets (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    session_exercise_id BIGINT NOT NULL,

    set_number INT NOT NULL,

    weight DECIMAL(6,2),

    reps INT,

    duration_seconds INT,

    distance_meters DECIMAL(8,2),

    rir INT,

    rpe DECIMAL(3,1),

    is_warmup BOOLEAN DEFAULT FALSE,

    completed BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_exercise_set_session_exercise
        FOREIGN KEY (session_exercise_id)
        REFERENCES session_exercises(id)
        ON DELETE CASCADE,

    CONSTRAINT uk_session_exercise_set
        UNIQUE(session_exercise_id, set_number),

    CONSTRAINT chk_weight_positive
        CHECK (weight >= 0),

    CONSTRAINT chk_reps_positive
        CHECK (reps >= 0),

    CONSTRAINT chk_duration_positive
        CHECK (duration_seconds >= 0),

    CONSTRAINT chk_distance_positive
        CHECK (distance_meters >= 0)
);

CREATE INDEX idx_sets_session
ON exercise_sets(session_exercise_id);



/*==============================================================
  TABLE: body_weight_logs
==============================================================*/

CREATE TABLE body_weight_logs (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    weight DECIMAL(5,2) NOT NULL,

    logged_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_body_weight_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_weight_user
ON body_weight_logs(user_id);

CREATE INDEX idx_weight_date
ON body_weight_logs(logged_at);


/*==============================================================
  TABLE: personal_records
==============================================================*/

CREATE TABLE personal_records (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    exercise_id BIGINT NOT NULL,

    weight DECIMAL(6,2),

    reps INT,

    estimated_one_rm DECIMAL(6,2),

    achieved_at TIMESTAMP,

    CONSTRAINT fk_pr_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_pr_exercise
        FOREIGN KEY (exercise_id)
        REFERENCES exercises(id),

    CONSTRAINT uk_user_exercise_pr
        UNIQUE(user_id, exercise_id)
);

CREATE INDEX idx_pr_user
ON personal_records(user_id);